#+TITLE: Add Two Problem
#+OPTIONS: toc:nil

* Problem Introduction
This is a problem from [[https://leetcode.com/problems/add-two-numbers/][leet code]], which is a really cool website! In fact, it might be nice to use
their site while attempting this problem because of their integrated test-cases. Fair warning 
though, I don't like their custom data-structures. I'd rather they just used the language default 
list structure.

** Description
#+BEGIN_QUOTE
You are given two non-empty linked lists representing two non-negative integers. The digits are 
stored in reverse order and each of their nodes contain a single digit. Add the two numbers and
return it as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.
#+END_QUOTE

#+begin_src 
Input: (2 -> 4 -> 3) + (5 -> 6 -> 4)
Output: 7 -> 0 -> 8
Explanation: 342 + 465 = 807.
#+end_src

* Test Cases
  From the leetcode example:
  #+begin_src 
  Given:
  [2, 4, 3]
  [5, 6, 4]

  Return:
  [7, 0, 8]
  #+end_src
  Adding numbers of unequal size:
  #+begin_src 
  Given:
  [2, 4, 3]
  [5]

  Return:
  [7, 4, 3]
  #+end_src
  Adding very large numbers:
  #+begin_src 
  Given:
  [3, 2, 2, 2, 5, 0, 4, 8, 6]
  [6, 0, 4, 8, 4, 6, 7, 7, 5, 1, 4, 5, 6, 7, 8]
  
  Return:
  [9, 2, 6, 0, 0, 7, 1, 6, 2, 2, 4, 5, 6, 7, 8]
  #+end_src
